version: "3.9"

services:
  sigmund-bot:
    image: ubuntu:22.04
    build:
      context: ./sigmund-bot/
      dockerfile: Dockerfile
      args:
        - SIGNAL_CLI=${VERSION}
    env_file:
      - .env
    #restart: always
    